from __future__ import annotations

from typing import Any

import sqlalchemy as sa
from pgvector.sqlalchemy import VECTOR

NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}
metadata = sa.MetaData(naming_convention=NAMING_CONVENTION)

REQUIRED_TABLES = (
    "users",
    "user_preferences",
    "projects",
    "project_aliases",
    "project_memberships",
    "requirements",
    "requirement_revisions",
    "decisions",
    "decision_revisions",
    "work_items",
    "work_item_dependencies",
    "milestones",
    "risks",
    "acceptance_criteria",
    "calendar_accounts",
    "calendar_events_cache",
    "calendar_links",
    "schedule_proposals",
    "conversations",
    "messages",
    "agent_runs",
    "agent_checkpoints",
    "memories",
    "memory_revisions",
    "memory_relations",
    "documents",
    "document_sources",
    "document_chunks",
    "embeddings",
    "connectors",
    "connector_capabilities",
    "tool_definitions",
    "tool_executions",
    "approval_requests",
    "approval_decisions",
    "audit_events",
    "scheduled_jobs",
    "notifications",
    "skills",
    "skill_versions",
    "generated_artifacts",
    "backup_runs",
    "resource_samples",
    "devices",
    "device_keys",
    "device_pairing_sessions",
    "mobile_sessions",
    "mobile_refresh_token_families",
    "worker_nodes",
    "worker_presence_events",
    "voice_sessions",
    "voice_transcripts",
    "realtime_client_secret_issuances",
    "approval_attestations",
    "push_subscriptions",
    "offline_command_envelopes",
    "usage_budgets",
    "usage_samples",
)


def _common_columns() -> list[sa.Column[Any]]:
    return [
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("owner_scope", sa.String(128), nullable=False, server_default="local-user"),
        sa.Column("version", sa.Integer(), nullable=False, server_default="1"),
        sa.Column("audit_metadata", sa.JSON(), nullable=False, server_default=sa.text("'{}'")),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.current_timestamp(),
        ),
    ]


SPECIAL_COLUMNS: dict[str, list[sa.Column[Any]]] = {
    "users": [
        sa.Column("display_name", sa.String(160), nullable=False),
        sa.Column("locale", sa.String(16), nullable=False, server_default="zh-TW"),
        sa.Column("timezone", sa.String(64), nullable=False, server_default="Asia/Taipei"),
    ],
    "projects": [
        sa.Column("name", sa.String(240), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="active"),
    ],
    "requirements": [
        sa.Column("project_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("statement", sa.Text(), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="draft"),
    ],
    "work_items": [
        sa.Column("project_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("title", sa.String(300), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, server_default="draft"),
        sa.Column("source_requirement_ids", sa.JSON(), nullable=False),
    ],
    "memories": [
        sa.Column("user_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("project_id", sa.Uuid(), nullable=True, index=True),
        sa.Column("scope", sa.String(128), nullable=False),
        sa.Column("memory_type", sa.String(32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("normalized_content", sa.Text(), nullable=False),
        sa.Column("source_type", sa.String(64), nullable=False),
        sa.Column("source_id", sa.String(256), nullable=True),
        sa.Column("source_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("importance", sa.Float(), nullable=False),
        sa.Column("sensitivity", sa.String(32), nullable=False),
        sa.Column("status", sa.String(32), nullable=False, index=True),
        sa.Column("valid_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("valid_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("supersedes_memory_id", sa.Uuid(), nullable=True),
        sa.Column("created_by", sa.String(128), nullable=False),
        sa.Column("approved_by", sa.String(128), nullable=True),
        sa.Column("content_hash", sa.String(64), nullable=False, index=True),
    ],
    "embeddings": [
        sa.Column("document_chunk_id", sa.Uuid(), nullable=True, index=True),
        sa.Column("memory_id", sa.Uuid(), nullable=True, index=True),
        sa.Column("model_id", sa.String(160), nullable=False),
        sa.Column("dimensions", sa.Integer(), nullable=False, server_default="768"),
        sa.Column("embedding", VECTOR(768).with_variant(sa.JSON(), "sqlite"), nullable=False),
        sa.Column("content_hash", sa.String(64), nullable=False, index=True),
    ],
    "tool_definitions": [
        sa.Column("name", sa.String(128), nullable=False, unique=True),
        sa.Column("risk_level", sa.String(64), nullable=False),
        sa.Column("input_schema", sa.JSON(), nullable=False),
        sa.Column("output_schema", sa.JSON(), nullable=False),
        sa.Column("requires_approval", sa.Boolean(), nullable=False),
    ],
    "approval_requests": [
        sa.Column("action_hash", sa.String(64), nullable=False, index=True),
        sa.Column("token_hash", sa.String(64), nullable=False),
        sa.Column("nonce", sa.String(128), nullable=False),
        sa.Column("risk_level", sa.String(64), nullable=False),
        sa.Column("state", sa.String(32), nullable=False, index=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
    ],
    "audit_events": [
        sa.Column("sequence", sa.BigInteger(), nullable=False, unique=True),
        sa.Column("event_type", sa.String(128), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("previous_hash", sa.String(64), nullable=True),
        sa.Column("event_hash", sa.String(64), nullable=False, unique=True),
    ],
    "devices": [
        sa.Column("user_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("display_name", sa.String(160), nullable=False),
        sa.Column("platform", sa.String(32), nullable=False),
        sa.Column("app_version", sa.String(32), nullable=False),
        sa.Column("os_version", sa.String(64), nullable=False),
        sa.Column("trust_state", sa.String(32), nullable=False, index=True),
        sa.Column("public_key_algorithm", sa.String(32), nullable=False),
        sa.Column("public_key", sa.Text(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    ],
    "device_pairing_sessions": [
        sa.Column("secret_hash", sa.String(64), nullable=False),
        sa.Column("comparison_code_hash", sa.String(64), nullable=False),
        sa.Column("server_fingerprint", sa.String(128), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
    ],
    "mobile_refresh_token_families": [
        sa.Column("device_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("current_token_hash", sa.String(64), nullable=False),
        sa.Column("used_token_hashes", sa.JSON(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
    ],
    "voice_transcripts": [
        sa.Column("voice_session_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("device_id", sa.Uuid(), nullable=True),
        sa.Column("state", sa.String(32), nullable=False),
        sa.Column("speaker", sa.String(32), nullable=False),
        sa.Column("provider", sa.String(64), nullable=False),
        sa.Column("locale", sa.String(16), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("retention_policy", sa.String(32), nullable=False),
        sa.Column("promoted_message_id", sa.Uuid(), nullable=True),
    ],
    "realtime_client_secret_issuances": [
        sa.Column("device_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("secret_hash", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("mode", sa.String(32), nullable=False),
        sa.Column("safety_identifier", sa.String(64), nullable=False),
    ],
    "offline_command_envelopes": [
        sa.Column("device_id", sa.Uuid(), nullable=False, index=True),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("action_hash", sa.String(64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("state", sa.String(32), nullable=False),
    ],
    "usage_budgets": [
        sa.Column("subject_id", sa.String(128), nullable=False, index=True),
        sa.Column("period_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("soft_limit", sa.BigInteger(), nullable=False),
        sa.Column("hard_limit", sa.BigInteger(), nullable=False),
        sa.Column("used", sa.BigInteger(), nullable=False, server_default="0"),
    ],
}

for table_name in REQUIRED_TABLES:
    sa.Table(
        table_name,
        metadata,
        *_common_columns(),
        *SPECIAL_COLUMNS.get(table_name, []),
    )
